app/urls.py
from django.urls import path, include
from app import views

urlpatterns = [
    # Index landing page
    path('', views.index_page, name='index'),
    path('inicio/', views.inicio, name = 'inicio'),
]

cursos/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [

    path('categoria_create/', views.CategoriaCreate.as_view(), name = 'categoria_create'),
    path('categoria_list/', views.CategoriaList.as_view(), name = 'categoria_list'),
	path('categoria_update/<int:pk>/', views.CategoriaUpdate.as_view(), name = 'categoria_update'),
	path('categoria_delete/<int:pk>/delete/', views.CategoriaDelete.as_view(), name='categoria_delete'),
    path('curso_create/', views.curso_create, name = 'curso_create'),
    path('curso_list/', views.CursoList.as_view(), name = 'curso_list'),
	path('curso_update/<int:pk>/', views.CursoUpdate.as_view(), name = 'curso_update'),
	path('curso_delete/<int:pk>/delete/', views.CursoDelete.as_view(), name='curso_delete'),
    path('inscripcion_curso/<int:pk>/', views.inscripcion_curso, name = 'inscripcion_curso'),
]

cursos_kirios/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('cursos/', include(('cursos.urls', 'cursos'), namespace='cursos')),
]
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    activo = models.BooleanField(default=True)

    def __str__(self):
    	return self.nombre

class Curso(models.Model):
    categoria = models.ForeignKey(Categoria,  on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    resumen = models.TextField()
    requisitos = models.TextField()
    image = models.ImageField(upload_to = 'static/img/curso')
    profesor = models.ForeignKey(User,  on_delete=models.CASCADE)
    fecha = models.DateField()
    cupos = models.IntegerField()
    inscritos = models.ManyToManyField(User, related_name="inscritos", blank = True)

    def __str__(self):
    	return self.titulo

class Inscripcion(models.Model):
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso,  on_delete=models.CASCADE)

    def __str__(self):
    	return self.user

cursos/forms.py
from django import forms
from .models import *

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        # fields = '__all__'
        fields = '__all__'

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        # fields = '__all__'
        fields = '__all__'
        widgets = {
            'resumen': forms.Textarea(attrs={'rows':2}),
            'requisitos':forms.Textarea(attrs={'rows':2}),
            'fecha': forms.DateInput(attrs = {'type':"date"})
        }

cursos/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.db import transaction
from django.contrib.auth.models import Group

from .models import *
from usuarios.forms import UserForm, UserInscripcion
from .models import *
from .forms import CategoriaForm, CursoForm
# Create your views here.
class CategoriaCreate(CreateView):
	model = Categoria
	form_class = CategoriaForm
	success_url = reverse_lazy('cursos:categoria_list')


class CategoriaList(ListView):
	model = Categoria


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	success_url = reverse_lazy('cursos:categoria_list')

class CategoriaDelete(DeleteView):
    model = Categoria
    success_url = reverse_lazy('cursos:categoria_list')

def curso_create(request):
    form = CursoForm()
    if request.method == 'POST':
        form= CursoForm(request.POST, request.FILES)
        if form.is_valid():
            curso = form.save()
            return redirect('cursos:curso_list')
    context = {
        'form': form,
    }

    return render(request, 'cursos/curso_form.html', context)
class CursoCreate(CreateView):
	model = Curso
	form_class = CursoForm
	success_url = reverse_lazy('cursos:curso_list')


class CursoList(ListView):
	model = Curso


class CursoUpdate(UpdateView):
	model = Curso
	form_class = CursoForm
	success_url = reverse_lazy('cursos:curso_list')

class CursoDelete(DeleteView):
    model = Curso
    success_url = reverse_lazy('cursos:curso_list')


# Create your views here.
@transaction.atomic
def inscripcion_curso(request, pk):
    '''Inscribe a un estudiante desde la pagina index'''
    curso = Curso.objects.get(pk = pk)
    user_form = UserInscripcion()
    if request.method == 'POST':
        user_form = UserInscripcion(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            user.groups.add(Group.objects.get(name='Estudiante'))
            curso.inscritos.add(user)

            messages.success(request, "Inscripcion guardada correctamente.")

            return redirect('index')
        else:
            print("Error Forms")
    context = {
               'curso': curso,
               'user_form': user_form,
    }
    return render(request, 'frontend/inscripcion_form.html', context)

templates/cursos/categoria_confirm_delete.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
<div class="app-body">
  <div class="row d-flex justify-content-center col-sm-12 col-xl-12" align="center">
    <div class="col-sm-8" >
      <div class="card">
        <div class="card-header">
          <strong>Advertencia !!!</strong></div>
        <div class="card-body">
         <form method="post">{% csrf_token %}
  		    <p>¿Está seguro que desea eliminar "{{ object }}"?</p>
  		    <div class="card-footer">
            <button class="btn btn-sm btn-success" type="submit">
              <i class="fa fa-dot-circle-o"></i>Si</button>
            <a class="btn btn-sm btn-danger"  href="{% url 'cursos:categoria_list' %}">
              <i class="fa fa-ban"></i>No</a>
          </div>
    		</form>
        </div>
      </div>
    </div>
    <div class="space-100"></div>
  </div>
</div>

{% endblock content %}
{% block javascripts %}
{{ block.super }}
{% endblock javascripts %}

templates/cursos/categoria_form.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}

  <div class="container">

    <div class="card o-hidden border-0 ">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row  align-self-center">
          <div class="col-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Crear Categoría</h1>
              </div>
              <form method="POST">
               {% csrf_token %}

                <div class="form-group col 3">
                  {% bootstrap_form form %}
                </div>
                <div class="col align-self-center">
                  <div class="card-footer">
                    <button class="btn btn-sm btn-primary" type="submit">
                      <i class="fas fa-save"></i> Guardar</button>
                    <a class="btn btn-sm btn-danger"  href="{% url 'cursos:categoria_list' %}">
                      <i class="fa fa-ban"></i> Cancelar</a>
                  </div>
              </div>

              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  {% endblock content %}

templates/cursos/categoria_list.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Lista de Categorías</h1>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">

            <div class="card-body">
              <a class="btn btn-sm btn-primary"  href="{% url 'cursos:categoria_create' %}">
                <i class="fas fa-external-link-alt"></i> Nuevo</a>
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Estado</th>
                      <th>Acciones</th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for categoria in object_list %}
                    <tr>
                      <td>{{ categoria.nombre }} </td>
                      <td>{{ categoria.activo }} </td>
                      <td>
                        <a href="{% url 'cursos:categoria_update' categoria.pk %}">
                          <span class="fas fa-pencil-alt font-2xl" aria-hidden="true" title="Editar"></span>
                        </a>
                        <a href="{% url 'cursos:categoria_delete' categoria.pk %}">
                          <span class="fas fa-trash-alt font-2xl" aria-hidden="true" title="Eliminar"></span>
                        </a>
                      </td>
                      {% endfor %}
                    </tr>

                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        {% endblock content %}

templates/cursos/curso_confirm_delete.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
<div class="app-body">
  <div class="row d-flex justify-content-center col-sm-12 col-xl-12" align="center">
    <div class="col-sm-8" >
      <div class="card">
        <div class="card-header">
          <strong>Advertencia !!!</strong></div>
        <div class="card-body">
         <form method="post">{% csrf_token %}
  		    <p>¿Está seguro que desea eliminar "{{ object }}"?</p>
  		    <div class="card-footer">
            <button class="btn btn-sm btn-success" type="submit">
              <i class="fa fa-dot-circle-o"></i>Si</button>
            <a class="btn btn-sm btn-danger"  href="{% url 'cursos:curso_list' %}">
              <i class="fa fa-ban"></i>No</a>
          </div>
    		</form>
        </div>
      </div>
    </div>
    <div class="space-100"></div>
  </div>
</div>

{% endblock content %}
{% block javascripts %}
{{ block.super }}
{% endblock javascripts %}

templates/cursos/curso_form.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}

  <div class="container">

    <div class="card o-hidden border-0 ">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row  align-self-center">
          <div class="col-12">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Crear Curso</h1>
              </div>
              <form method="POST" enctype="multipart/form-data">
               {% csrf_token %}

                <div class="form-group col 3">
                  {% bootstrap_form form %}
                </div>
                <div class="col align-self-center">
                  <div class="card-footer">
                    <button class="btn btn-sm btn-primary" type="submit">
                      <i class="fas fa-save"></i> Guardar</button>
                    <a class="btn btn-sm btn-danger"  href="{% url 'cursos:curso_list' %}">
                      <i class="fa fa-ban"></i> Cancelar</a>
                  </div>
              </div>

              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  {% endblock content %}

templates/cursos/curso_list.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Lista de Cursos</h1>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">

            <div class="card-body">
              <a class="btn btn-sm btn-primary"  href="{% url 'cursos:curso_create' %}">
                <i class="fas fa-external-link-alt"></i> Nuevo</a>
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Categoria</th>
                      <th>Titulo</th>
                      <th>Resumen</th>
                      <th>Requisitos</th>
                      <th>Imagen</th>
                      <th>Profesor</th>
                      <th>Fecha</th>
                      <th>Cupos</th>
                      <th>Acciones</th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for curso in object_list %}
                    <tr>
                      <td>{{ curso.categoria }} </td>
                      <td>{{ curso.titulo }} </td>
                      <td>{{ curso.resumen }} </td>
                      <td>{{ curso.requisitos }} </td>
                      <td >
                          <div class="thumb">
                              <img src="{{ curso.image.url }}" width="70"  style="border-radius: 1em !important;">
                          </div>
                      </td>
                      <td>{{ curso.profesor }} </td>
                      <td>{{ curso.fecha }} </td>
                      <td>{{ curso.cupos }} </td>
                      <td>
                        <a href="{% url 'cursos:curso_update' curso.pk %}">
                          <span class="fas fa-pencil-alt font-2xl" aria-hidden="true" title="Editar"></span>
                        </a>
                        <a href="{% url 'cursos:curso_delete' curso.pk %}">
                          <span class="fas fa-trash-alt font-2xl" aria-hidden="true" title="Eliminar"></span>
                        </a>
                      </td>
                      {% endfor %}
                    </tr>

                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        {% endblock content %}