app/urls.py
from django.urls import path, include
from app import views

urlpatterns = [
    # Index landing page
    path('', views.index_page, name='index'),
    path('inicio/', views.inicio, name = 'inicio'),
]

cursos_kirios/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('cursos/', include(('cursos.urls', 'cursos'), namespace='cursos')),
]
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [

    path('usuario_create/', views.usuario_create, name = 'usuario_create'),
    path('usuario_list/', views.usuario_list, name = 'usuario_list'),
    path('usuario_edit/<int:pk>/', views.usuario_edit, name = 'usuario_edit'),
    path('usuario_delete/<int:pk>/', views.usuario_delete, name = 'usuario_delete'),
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = (
				'first_name',
				'last_name',
				'username',
				'email',
                'groups',
                'password',
				)


class UserInscripcion(forms.ModelForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = (
				'first_name',
				'last_name',
				'username',
				'email',
                'password',
				)
        widgets = {
        'password': forms.PasswordInput(),
        }

usuarios/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth.models import User
from .models import *
# Create your views here.
def usuario_create(request):
    form = UserForm()
    if request.method == 'POST':
        form= UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            return redirect('usuarios:usuario_list')
    else:
        context = {
            'form': form,
            'titulo': 'Crear Usuario'
        }

    return render(request, 'usuarios/usuario_create.html', context)


def usuario_list(request):
    usuarios = User.objects.all()
    context = {
        'usuarios': usuarios,
    }
    return render(request, 'usuarios/usuario_list.html', context)

def usuario_edit(request, pk):
    usuario = User.objects.get(pk=pk)
    usuario_form = UserForm(instance = usuario)
    if request.method == "POST":
        usuario_form = UserForm(request.POST, instance=usuario)
        if usuario_form.is_valid():
            usuario_form.save()
            return redirect('usuarios:usuario_list')
    context = {
        'form': usuario_form,
        'titulo': 'Editar Usuario'
    }

    return render(request, 'usuarios/usuario_create.html', context)


def usuario_delete(request, pk):
    usuario = User.objects.get(pk=pk)
    usuario.delete()
    return redirect('usuarios:usuario_list')

templates/usuarios/usuario_create.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}

  <div class="container">

    <div class="card o-hidden border-0 ">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row  align-self-center">
          <div class="col-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">{{titulo}}</h1>
              </div>
              <form method="POST">
               {% csrf_token %}

                <div class="form-group col 3">
                  {% bootstrap_form form %}
                </div>
                <div class="col align-self-center">
                  <div class="card-footer">
                    <button class="btn btn-sm btn-primary" type="submit">
                      <i class="fas fa-save"></i> Guardar</button>
                    <a class="btn btn-sm btn-danger"  href="{% url 'usuarios:usuario_list' %}">
                      <i class="fa fa-ban"></i> Cancelar</a>
                  </div>
              </div>

              </form>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  {% endblock content %}

templates/usuarios/usuario_list.html
{% extends "backend/base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Lista de Usuarios</h1>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">

            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Apellido</th>
                      <th>Username</th>
                      <th>Correo</th>
                      <th>Rol</th>
                      <th>Acciones</th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for usuario in usuarios %}
                    <tr>
                      <td>{{ usuario.first_name }} </td>
                      <td>{{ usuario.last_name }} </td>
                      <td>{{ usuario.username }} </td>
                      <td>{{ usuario.email }} </td>
                      {% for rol in usuario.groups.all %}
                      <td>{{ rol }} </td>
                      {% endfor %}
                      <td>
                        <a href="{% url 'usuarios:usuario_edit' usuario.pk %}">
                          <span class="fas fa-pencil-alt font-2xl" aria-hidden="true" title="Editar"></span>
                        </a>
                        <a href="{% url 'usuarios:usuario_delete' usuario.pk %}">
                          <span class="fas fa-trash-alt font-2xl" aria-hidden="true" title="Eliminar"></span>
                        </a>
                      </td>
                      {% endfor %}
                    </tr>

                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        {% endblock content %}